services:
  postgres:
    image: postgres:16-alpine
    container_name: stages-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: stages_user
      POSTGRES_PASSWORD: stages_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stages-network

    # Service d'authentification
  auth-service:
    build:
      context: ./backend
      dockerfile: services/auth/Dockerfile
    container_name: stages-auth
    restart: unless-stopped
    environment:
      PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: stages_user
      POSTGRES_PASSWORD: stages_password
      POSTGRES_DB: postgres
      JWT_SECRET: 'Er3vsrwb3y35GN6kQH9fFs6HdQnqMh+WV0uJiQHUkvuFZMSczD/jf/wMCA31Jx2a WvZZaRkylQ9iCqcToLNpOQ=='
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - stages-network

  # Service de gestion des stages/carte
  stage-service:
    build:
      context: ./backend
      dockerfile: services/stage/Dockerfile
    container_name: stages-map
    restart: unless-stopped
    environment:
      PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: stages_user
      POSTGRES_PASSWORD: stages_password
      POSTGRES_DB: postgres
      JWT_SECRET: 'Er3vsrwb3y35GN6kQH9fFs6HdQnqMh+WV0uJiQHUkvuFZMSczD/jf/wMCA31Jx2a WvZZaRkylQ9iCqcToLNpOQ=='
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - stages-network

  # Service de gestion des entreprises
  enterprise-service:
    build:
      context: ./backend
      dockerfile: services/enterprise/Dockerfile
    container_name: stages-enterprise
    restart: unless-stopped
    environment:
      PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: stages_user
      POSTGRES_PASSWORD: stages_password
      POSTGRES_DB: postgres
      JWT_SECRET: 'Er3vsrwb3y35GN6kQH9fFs6HdQnqMh+WV0uJiQHUkvuFZMSczD/jf/wMCA31Jx2a WvZZaRkylQ9iCqcToLNpOQ=='
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - stages-network

  student-service:
    build:
      context: ./backend
      dockerfile: services/student/Dockerfile
    container_name: stages-student
    restart: unless-stopped
    environment:
      PORT: 80
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: stages_user
      POSTGRES_PASSWORD: stages_password
      POSTGRES_DB: postgres
      JWT_SECRET: 'Er3vsrwb3y35GN6kQH9fFs6HdQnqMh+WV0uJiQHUkvuFZMSczD/jf/wMCA31Jx2a WvZZaRkylQ9iCqcToLNpOQ=='
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - stages-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_API_URL=http://localhost
    container_name: stages-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_URL: http://localhost
    expose:
      - "443"
    depends_on:
      - auth-service
      - stage-service
      - enterprise-service
    networks:
      - stages-network

  nginx:
    image: nginx:alpine
    container_name: stages-nginx
    restart: unless-stopped
    volumes:
      # Pour dev local (HTTP uniquement)
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro

      # Pour production (HTTPS)
      # - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      # - /etc/letsencrypt:/etc/ssl:ro
    ports:
      - "80:80"
      # - "443:443"  # Commenté pour dev local
    depends_on:
      - auth-service
      - stage-service
      - enterprise-service
      - frontend
    networks:
      - stages-network



volumes:
  postgres_data:
    driver: local

networks:
  stages-network:
    driver: bridge
